apiVersion: v1
kind: Service
metadata:
  name: study-app        # <-- troque de study-app-service para study-app
  namespace: dev-study
spec:
  selector:
    app: study-app       # <-- igual ao label do Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort