name: CI/CD Pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Testar aplicação
        run: npm test || echo "Nenhum teste configurado"

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tags: ghcr.io/${{ github.repository_owner }}/pipeline/study-app:latest

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev-study
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.29.0"

      - name: Configurar acesso ao cluster DEV
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Aplicar manifests DEV
        run: |
          kubectl apply -f k8s/deployment.yaml -n dev-study
          kubectl apply -f k8s/service.yaml -n dev-study

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    environment: prod-study
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.29.0"

      - name: Configurar acesso ao cluster PROD
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Aplicar manifests PROD
        run: |
          kubectl apply -f k8s/deployment.yaml -n prod-study
          kubectl apply -f k8s/service.yaml -n prod-study