name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker para GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem
        run: |
          docker build -t ghcr.io/orbite82/pipeline/study-app:latest .

      - name: Push da imagem para GHCR
        run: |
          docker push ghcr.io/orbite82/pipeline/study-app:latest

      - name: Configurar kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_DEV }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
        if: github.ref == 'refs/heads/dev'

      - name: Deploy em DEV
        run: |
          kubectl apply -f k8s/deployment-dev.yaml
          kubectl rollout status deployment study-app -n dev-study
        if: github.ref == 'refs/heads/dev'

      - name: Configurar kubectl (PROD)
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
        if: github.ref == 'refs/heads/main'

      - name: Deploy em PROD
        run: |
          kubectl apply -f k8s/deployment-prod.yaml
          kubectl rollout status deployment study-app -n prod-study
        if: github.ref == 'refs/heads/main'