name: CI/CD Pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Instalar dependências
        run: npm install

      - name: Testar aplicação
        run: npm test || echo "Nenhum teste configurado"

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: orbite82
          password: ${{ secrets.GHCR_PIPELINE_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/orbite82/pipeline/study-app:latest

  deploy-dev:
    runs-on: self-hosted
    needs: build
    environment: dev-study
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.29.0"

      - name: Configurar acesso ao cluster DEV
        run: |
          printf "%s" "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Garantir namespace DEV
        run: kubectl create namespace dev-study --dry-run=client -o yaml | kubectl apply -f -

      - name: Aplicar manifests DEV
        run: |
          kubectl apply -f k8s/deployment.yaml -n dev-study
          kubectl apply -f k8s/service.yaml -n dev-study

      - name: Validar rollout do deployment
        run: kubectl rollout status deployment study-app -n dev-study

      - name: Validar Service DEV
        run: kubectl get svc study-app -n dev-study

      - name: Testar endpoint de saúde
        run: |
          kubectl run tmp-test --rm --restart=Never --attach --image=curlimages/curl -n dev-study -- \
          curl -s http://study-app:80/health

  deploy-prod:
    runs-on: self-hosted
    needs: build
    environment: prod-study
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.29.0"

      - name: Configurar acesso ao cluster PROD
        run: |
          printf "%s" "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Garantir namespace PROD
        run: kubectl create namespace prod-study --dry-run=client -o yaml | kubectl apply -f -

      - name: Aplicar manifests PROD
        run: |
          kubectl apply -f k8s/deployment.yaml -n prod-study
          kubectl apply -f k8s/service.yaml -n prod-study